import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import test from 'node:test'

const pagesSource = readFileSync(new URL('../src/pages.tsx', import.meta.url), 'utf8')
const chartWorkspaceSource = readFileSync(new URL('../src/components/ChartWorkspace.tsx', import.meta.url), 'utf8')
const marketOverviewSource = readFileSync(new URL('../src/components/MarketOverview.tsx', import.meta.url), 'utf8')
const marketHeatmapSource = readFileSync(new URL('../src/components/MarketHeatmap.tsx', import.meta.url), 'utf8')
const mainSource = readFileSync(new URL('../src/main.tsx', import.meta.url), 'utf8')
const baseStyles = readFileSync(new URL('../src/styles/base.css', import.meta.url), 'utf8')
const marketStyles = readFileSync(new URL('../src/styles/market.css', import.meta.url), 'utf8')
const operationsStyles = readFileSync(new URL('../src/styles/operations.css', import.meta.url), 'utf8')
const optionStyles = readFileSync(new URL('../src/styles/options.css', import.meta.url), 'utf8')
const responsiveStyles = readFileSync(new URL('../src/styles/responsive.css', import.meta.url), 'utf8')
const componentStyles = readFileSync(new URL('../src/styles/components.css', import.meta.url), 'utf8')
const drawingLayerSource = readFileSync(new URL('../src/components/ChartDrawingLayer.tsx', import.meta.url), 'utf8')
const marketChartSource = readFileSync(new URL('../src/components/MarketChart.tsx', import.meta.url), 'utf8')
const marketCalendarSource = readFileSync(new URL('../src/components/MarketEventCalendar.tsx', import.meta.url), 'utf8')
const selectFieldSource = readFileSync(new URL('../src/components/ui/SelectField.tsx', import.meta.url), 'utf8')
const optionWorkspaceSource = readFileSync(new URL('../src/components/OptionResearchWorkspace.tsx', import.meta.url), 'utf8')
const timeframeDropdownSource = readFileSync(new URL('../src/components/ui/TimeframeDropdown.tsx', import.meta.url), 'utf8')
const welcomeStyles = readFileSync(new URL('../src/styles/welcome.css', import.meta.url), 'utf8')
const indexSource = readFileSync(new URL('../index.html', import.meta.url), 'utf8')
const themeInitSource = readFileSync(new URL('../public/theme-init.js', import.meta.url), 'utf8')
const appSource = readFileSync(new URL('../src/App.tsx', import.meta.url), 'utf8')
const appShellSource = readFileSync(new URL('../src/components/AppShell.tsx', import.meta.url), 'utf8')
const loginPageSource = readFileSync(new URL('../src/pages/LoginPage.tsx', import.meta.url), 'utf8')
const themeSource = readFileSync(new URL('../src/theme.ts', import.meta.url), 'utf8')
const reportsSource = readFileSync(new URL('../src/pages/ReportsPage.tsx', import.meta.url), 'utf8')
const professionalLabSource = readFileSync(new URL('../src/pages/ProfessionalLabPage.tsx', import.meta.url), 'utf8')
const clientSource = readFileSync(new URL('../src/api/client.ts', import.meta.url), 'utf8')
const workspaceContextSource = readFileSync(new URL('../src/api/WorkspaceContext.tsx', import.meta.url), 'utf8')

test('Simplified and Traditional Chinese fonts are bundled locally without Google font runtime failures', () => {
  assert.match(mainSource, /@fontsource-variable\/noto-sans-tc\/wght\.css/)
  assert.match(mainSource, /@fontsource-variable\/noto-sans-sc\/wght\.css/)
  assert.doesNotMatch(mainSource, /@fontsource\/ibm-plex-mono/)
  assert.doesNotMatch(baseStyles, /fonts\.googleapis\.com/)
  assert.match(baseStyles, /--font-hant: 'Noto Sans TC Variable'/)
  assert.match(baseStyles, /--font-hans: 'Noto Sans SC Variable'/)
  assert.match(baseStyles, /--font-label: var\(--font-ui\)/)
  assert.match(baseStyles, /--font-number: var\(--font-ui\)/)
  assert.match(baseStyles, /--mono: var\(--font-ui\)/)
  assert.match(baseStyles, /font-synthesis: none/)
  assert.match(welcomeStyles, /font-family: var\(--font-ui\)/)
})

test('research keeps one chart-first workspace with an internal collapsible tool panel', () => {
  assert.match(pagesSource, /matchMedia\('\(min-width: 1071px\)'\)/)
  assert.match(pagesSource, /const researchToolPanel = <div className="research-tool-panel-inner">/)
  assert.match(pagesSource, /toolPanel=\{researchToolPanel\}/)
  assert.match(pagesSource, /toolPanelLabel="研究工具"/)
  assert.match(pagesSource, /inspectorOpen=\{inspectorOpen\}/)
  assert.match(pagesSource, /onInspectorOpenChange=\{setInspectorOpen\}/)
  assert.doesNotMatch(pagesSource, /inspectorExtra=\{auxiliaryInspector\}/)
  assert.doesNotMatch(pagesSource, /research-ai-column/)
  assert.doesNotMatch(pagesSource, /<aside className="market-inspector">/)
  assert.match(marketStyles, /grid-template-columns: 202px minmax\(0, 1fr\)/)
  assert.match(marketStyles, /\.market-workspace\.research-market-workspace \{ grid-template-columns: minmax\(0, 1fr\); \}/)
  assert.doesNotMatch(pagesSource, /<aside className="watchlist-panel"/)
  assert.doesNotMatch(marketStyles, /\.market-inspector/)
  assert.match(responsiveStyles, /@media \(max-width: 980px\) \{[\s\S]*?\.chart-workbench-inspector \{ position: absolute/)
  assert.doesNotMatch(responsiveStyles, /@media \(max-width: 1070px\)/)
  assert.match(chartWorkspaceSource, /const TOOL_PANEL_STORAGE_KEY = 'ciclotrade:chart-tool-panel-open:v1'/)
  assert.match(chartWorkspaceSource, /return localStorage\.getItem\(TOOL_PANEL_STORAGE_KEY\) !== 'collapsed'/)
  assert.match(chartWorkspaceSource, /className="chart-tool-panel"/)
  assert.match(chartWorkspaceSource, /aria-expanded=\{toolPanelOpen\}/)
  assert.match(marketStyles, /\.chart-tool-panel \{[\s\S]*?width: 220px/)
  assert.match(marketStyles, /\.is-tool-panel-collapsed \.chart-tool-panel \{ width: 43px/)
  assert.ok(
    chartWorkspaceSource.indexOf('className="chart-tool-panel"') < chartWorkspaceSource.indexOf('className={`multi-chart-grid'),
    'the research tool panel should live inside the chart body before the chart grid',
  )
})

test('market discovery pages eight desktop cards in a four by two grid while mobile limits four cards to a snap strip', () => {
  assert.match(marketOverviewSource, /className="market-overview" data-market=\{market\}/)
  assert.match(marketOverviewSource, /const DESKTOP_CARD_PAGE_SIZE = 8/)
  assert.match(marketOverviewSource, /const MOBILE_CARD_LIMIT = 4/)
  assert.match(marketOverviewSource, /shown\.slice\(0, MOBILE_CARD_LIMIT\)/)
  assert.match(marketOverviewSource, /\(cardsPage - 1\) \* DESKTOP_CARD_PAGE_SIZE/)
  assert.match(marketOverviewSource, /overview-card-pagination/)
  assert.match(marketStyles, /grid-template-columns: repeat\(4, minmax\(0, 1fr\)\)/)
  assert.match(responsiveStyles, /\.market-overview \.overview-card-grid \{ grid-template-columns: repeat\(2, minmax\(0, 1fr\)\); \}/)
  assert.match(responsiveStyles, /\.overview-card-grid \{ display: grid; grid-auto-flow: column/)
  assert.match(responsiveStyles, /scroll-snap-type: x mandatory/)
  assert.match(responsiveStyles, /\.overview-card-pagination \{ display: none; \}/)
  assert.match(marketOverviewSource, /K线工作图/)
  assert.match(marketOverviewSource, /variant="label"/)
})

test('market heatmap separates authoritative industry taxonomy from unconnected market themes', () => {
  for (const field of ['taxonomy_source', 'taxonomy_code', 'taxonomy_level', 'label', 'return_pct', 'constituent_count', 'as_of']) {
    assert.match(marketHeatmapSource, new RegExp(field))
  }
  assert.match(marketHeatmapSource, /行业热力图暂不可用/)
  assert.match(marketHeatmapSource, /行业组与行业不会在同一层级混放/)
  assert.match(marketHeatmapSource, /不绘制涨跌方块、不排序，也不提供代表股票/)
  assert.match(marketHeatmapSource, /市场主题 \/ 概念/)
  assert.match(marketHeatmapSource, /“光通信”等市场主题只会进入独立主题合同/)
  assert.doesNotMatch(marketHeatmapSource, /MSCI|S&P|GICS|data-taxonomy-source|data-taxonomy-code|data-direction|代表标的/)
  assert.doesNotMatch(marketOverviewSource, /onOpenSymbol=/)
  assert.match(marketStyles, /\.market-heatmap-empty \{[\s\S]*?border-bottom: 1px solid var\(--border\)/)
})

test('chart controls keep source identity private while retaining the desktop and keyboard contracts', () => {
  assert.doesNotMatch(chartWorkspaceSource, /<select[^>]*时间周期/)
  assert.match(chartWorkspaceSource, /TimeframeDropdown/)
  assert.doesNotMatch(timeframeDropdownSource, /createPortal/)
  assert.match(timeframeDropdownSource, /return <div className="timeframe-dropdown" ref=\{rootRef\}>/)
  assert.match(timeframeDropdownSource, /menuRef/)
  assert.match(timeframeDropdownSource, /optionRefs/)
  assert.match(timeframeDropdownSource, /triggerRef\.current\?\.focus/)
  assert.match(timeframeDropdownSource, /window\.addEventListener\('scroll', reposition, true\)/)
  assert.match(timeframeDropdownSource, /placement === 'top'/)
  assert.match(componentStyles, /timeframe-dropdown-menu/)
  assert.match(chartWorkspaceSource, /displayDataSource\(quote\.source\)/)
  assert.match(pagesSource, /displayDataSource\(payload\.status\.display_source\)/)
  assert.match(pagesSource, /activeTab === '期权证据'.*options-tab-cta/)
  assert.match(chartWorkspaceSource, /<div className="workbench-title">[\s\S]*?<strong>K线工作图<\/strong>[\s\S]*?<WatchlistToggle[\s\S]*?className="workbench-watchlist-toggle"[\s\S]*?<\/div>\s*<div className="multi-chart-layout-picker"/)
  assert.doesNotMatch(chartWorkspaceSource, /definition\.label} · \{marketLabel\(activeSlot\.market\)/)
  assert.match(chartWorkspaceSource, /toolbarActions\?: ReactNode/)
  assert.match(chartWorkspaceSource, /multi-chart-utility-actions/)
  assert.doesNotMatch(chartWorkspaceSource, /marketBrowserOpen|chart-market-browser|multi-chart-footer/)
  assert.doesNotMatch(pagesSource, /chart-toolbar-bottom/)
  assert.match(pagesSource, /toolbarActions=\{<>[\s\S]*?查看盘口与资料[\s\S]*?查看技术指标[\s\S]*?图表设置[\s\S]*?<\/>\}/)
  assert.match(marketStyles, /\.chart-frame \{[\s\S]*?height: clamp\(600px, calc\(100dvh - var\(--topbar-height\) - var\(--status-height\) - 72px\), 860px\);[\s\S]*?min-height: 600px;/)
  assert.doesNotMatch(pagesSource, /instrument-watch-toggle/)
  assert.match(componentStyles, /\.timeframe-dropdown-trigger \{[\s\S]*?height: 32px/)
  assert.match(componentStyles, /@media \(pointer: coarse\) \{[\s\S]*?\.timeframe-dropdown-trigger,[\s\S]*?min-height: 44px/)
  assert.match(marketStyles, /@media \(pointer: coarse\) \{[\s\S]*?\.chart-view-popover button,[\s\S]*?min-height: 44px/)
  assert.match(marketStyles, /\.drawing-tool-dock::-webkit-scrollbar \{ display: none; \}/)
  assert.match(drawingLayerSource, /scrollHorizontalDock/)
  assert.match(drawingLayerSource, /matchMedia\(horizontalDockQuery\)/)
  assert.doesNotMatch(responsiveStyles, /\.multi-chart-layouts/)
  assert.match(responsiveStyles, /\.multi-chart-layout-picker/)
  assert.match(responsiveStyles, /\.drawing-tool-dock button \{ width: 44px; height: 44px;/)
  assert.match(reportsSource, /displayDataSource\(workspace\.data\?\.performance\.mark_source/)
  assert.match(professionalLabSource, /displayDataSource\(workspace\.data\?\.market_data\.display_source/)
  assert.doesNotMatch(reportsSource, /recorded_system_snapshot/)
  assert.match(operationsStyles, /\.report-layout \{ align-items: stretch; \}/)
})

test('risk rings and the options workbench retain their institutional viewport contracts', () => {
  assert.match(operationsStyles, /\.lab-risk-workbench/)
  assert.match(operationsStyles, /\.metric-ring-dial/)
  assert.match(operationsStyles, /conic-gradient\(var\(--metric-ring-color\) calc\(var\(--metric-ring-value\) \* 1%\)/)
  assert.match(optionStyles, /\.lab-tab-options > \.page-header/)
  assert.match(optionStyles, /height: calc\(100dvh - var\(--topbar-height\) - var\(--status-height\)\)/)
  assert.match(optionStyles, /align-items: stretch/)
  assert.match(optionStyles, /height: 100%; max-height: 100%; grid-template-rows: auto minmax\(0, 1fr\)/)
  assert.match(optionStyles, /max-height: 560px/)
  assert.match(optionStyles, /\.lab-tab-options \.option-workbench \{ height: auto; min-height: 0; grid-row: -2 \/ -1; \}/)
  assert.match(optionStyles, /\.option-chart-panel\[data-detail-active='true'\],[\s\S]*?\.option-combination-panel\[data-detail-active='true'\] \{ display: none; \}/)
  assert.match(optionStyles, /\.lab-tab-options \.option-workbench \{ height: auto; min-height: 220px; grid-row: -2 \/ -1; grid-template-rows: 40px minmax\(0, 1fr\); gap: 4px; \}/)
})

test('theme canvas is applied before React and shared by public and console controls', () => {
  assert.match(baseStyles, /--canvas: hsl\(220 38% 4%\)/)
  assert.match(baseStyles, /:root\[data-theme='light'\] \{[\s\S]*?--canvas: hsl\(220 38% 98%\)/)
  assert.match(baseStyles, /--workspace: hsl\(220 34% 95%\)[\s\S]*?--surface: hsl\(220 30% 100%\)[\s\S]*?--surface-raised: hsl\(220 30% 98%\)[\s\S]*?--surface-inset: hsl\(220 30% 96%\)/)
  assert.match(baseStyles, /--sidebar: var\(--canvas\)[\s\S]*?--sidebar-selected: var\(--nav-active-bg\)/)
  assert.doesNotMatch(baseStyles, /--surface-raised: #(?:fff|ffffff)/)
  assert.match(indexSource, /<script src="\/theme-init\.js"><\/script>/)
  assert.doesNotMatch(indexSource, /<script>\s*\(function/)
  assert.match(themeInitSource, /localStorage\.getItem\('ciclotrade\.theme'\) === 'light'/)
  assert.match(themeInitSource, /root\.dataset\.theme = theme/)
  assert.match(themeInitSource, /themeColor\.setAttribute\('content', theme === 'light' \? 'hsl\(220 38% 98%\)' : 'hsl\(220 38% 4%\)'\)/)
  assert.match(themeSource, /THEME_CANVAS[\s\S]*?dark: 'hsl\(220 38% 4%\)'[\s\S]*?light: 'hsl\(220 38% 98%\)'/)
  assert.match(appSource, /from '\.\/theme'/)
  assert.match(appShellSource, /from '\.\.\/theme'/)
  assert.match(loginPageSource, /from '\.\.\/theme'/)
  assert.doesNotMatch(appSource, /ciclotrade\.theme/)
  assert.doesNotMatch(appShellSource, /theme-color/)
  assert.doesNotMatch(loginPageSource, /theme-color/)
})

test('coarse pointers retain 44px option and authentication controls without reducing landscape workbench space', () => {
  assert.match(welcomeStyles, /@media \(pointer: coarse\) \{[\s\S]*?\.login-mode-tabs button \{ min-height: 44px; \}/)
  assert.match(optionStyles, /@media \(pointer: coarse\) \{[\s\S]*?\.option-task-tabs button,[\s\S]*?\.option-chart-controls select \{ min-height: 44px; \}/)
  assert.match(optionStyles, /\.lab-tab-options \.option-workbench \{ grid-template-rows: 44px minmax\(0, 1fr\); \}/)
  assert.match(optionStyles, /\.lab-tab-options \.option-workbench \{ height: auto; min-height: 220px;/)
})

test('market refresh effects keep stable lifetimes and never expose raw provider freshness', () => {
  assert.match(chartWorkspaceSource, /const primaryQuoteExternallyManaged = initialQuote !== undefined/)
  assert.match(chartWorkspaceSource, /primaryQuoteExternallyManaged, primarySlotId, quoteFetchSignature/)
  assert.doesNotMatch(chartWorkspaceSource, /\[initialMarket, initialQuote, initialSymbol, loadQuote/)
  assert.match(chartWorkspaceSource, /if \(!hasPreviousQuote\) \{[\s\S]*?读取报价中/)
  assert.match(chartWorkspaceSource, /quoteInFlightRef[\s\S]*?previousRequest\?\.identity === identity[\s\S]*?previousRequest\.request/)
  assert.match(marketOverviewSource, /displayDeliveryDelay\(payload\.status\.delivery_delay_minutes\) \|\| displayFreshness/)
  assert.match(appShellSource, /const marketFreshness = displayFreshness\(marketStatus\?\.freshness\)/)
  assert.doesNotMatch(appShellSource, /marketStatus\?\.freshness\s*\?\?/)
  assert.match(clientSource, /request<unknown>\('\/api\/rewrite\/v1\/market\/status'\)/)
  assert.match(clientSource, /validMarketStatusPayload/)
  assert.match(workspaceContextSource, /createVisibilityPolling\(async \(\) => \{[\s\S]*?fetchMarketStatus\(\)[\s\S]*?\}, 15_000\)/)
})

test('authenticated market pages fail closed and chart timestamps use the fixed Hong Kong display clock', () => {
  assert.match(pagesSource, /loadCandles=\{marketDataEnabled \? loadWorkspaceCandles : undefined\}/)
  assert.match(marketOverviewSource, /行情连接未启用，不显示演示行情/)
  assert.match(marketOverviewSource, /marketDataEnabled: boolean/)
  assert.match(marketOverviewSource, /demoMode: boolean/)
  assert.match(marketOverviewSource, /if \(demoMode\)/)
  assert.match(chartWorkspaceSource, /市场未连接|marketLabel\(slot\.market\)/)
  assert.doesNotMatch(chartWorkspaceSource, /className="chart-quick-timeframes"/)
  assert.doesNotMatch(chartWorkspaceSource, /chart-range-presets|RANGE_PRESETS/)
  assert.doesNotMatch(marketStyles, /chart-range-presets|grid-template-rows: auto minmax\(0, 1fr\) 28px/)
  assert.match(marketChartSource, /timeZone: 'Asia\/Hong_Kong'/)
  assert.match(marketChartSource, /typeof value === 'object'/)
  assert.match(marketChartSource, /日线以美国交易日归档/)
  assert.match(marketChartSource, /chart-crosshair-card/)
  assert.match(marketChartSource, /当前盘口/)
  assert.match(marketChartSource, /盘口为当前报价，不代表所观察历史 K 线/)
  assert.match(marketChartSource, /onPointerDownCapture=\{onChartPointerDown\}/)
  assert.match(marketChartSource, /onPointerMoveCapture=\{onChartPointerMove\}/)
  assert.match(marketChartSource, /onPointerUpCapture=\{onChartPointerUp\}/)
  assert.match(marketChartSource, /onPointerCancelCapture/)
  assert.match(marketChartSource, /CHART_TOUCH_LONG_PRESS_MS/)
  assert.match(marketChartSource, /event\.preventDefault\(\)[\s\S]*?event\.stopPropagation\(\)/)
  assert.match(chartWorkspaceSource, /definition\.count > 1[\s\S]*?chart-symbol-trigger/)
  assert.match(chartWorkspaceSource, /definition\.count > 1 && <nav className="mobile-chart-tabs"/)
  assert.match(chartWorkspaceSource, /className="mobile-chart-inline-actions"/)
  assert.doesNotMatch(chartWorkspaceSource, /className="mobile-chart-tools"/)
  assert.doesNotMatch(chartWorkspaceSource, /className="mobile-chart-tools-popover"/)
  assert.match(chartWorkspaceSource, /chart-symbol-chips/)
  assert.match(chartWorkspaceSource, /watchlistSymbols\?: Partial<Record<Market, readonly string\[\]>>/)
  assert.match(chartWorkspaceSource, /const authoritativeWatchlist = typeof watchlistSymbols === 'function'/)
  assert.match(chartWorkspaceSource, /输入其他股票代码/)
  assert.doesNotMatch(chartWorkspaceSource, /quote-spread-strip/)
  assert.doesNotMatch(chartWorkspaceSource, /className="chart-view-controls"/)
  assert.match(marketStyles, /\.chart-slot \{[\s\S]*?grid-template-rows: 32px minmax\(0, 1fr\)/)
  assert.doesNotMatch(marketStyles, /min-height: 66px; grid-template-columns/)
  assert.match(marketChartSource, /rightPriceScale: \{ borderColor: chartBorder, minimumWidth: 62 \}/)
  assert.match(responsiveStyles, /@media \(max-width: 600px\) \{[\s\S]*?\.chart-frame \{ height: max\(64dvh, 480px\); min-height: max\(50dvh, 480px\); max-height: none; \}/)
  assert.match(responsiveStyles, /\.multi-chart-grid:has\(\.mobile-chart-tabs\) \{ grid-template-rows: 44px minmax\(0, 1fr\)/)
  assert.match(responsiveStyles, /\.multi-chart-utility-actions \{ display: none; \}/)
  assert.match(responsiveStyles, /\.multi-chart-layout-picker \{ display: none; \}/)
  assert.match(responsiveStyles, /\.chart-slot-toolbar \.chart-focus-control, \.chart-slot-toolbar \.chart-view-menu \{ display: none; \}/)
  assert.match(responsiveStyles, /\.mobile-chart-inline-actions \{ display: flex;/)
  assert.match(responsiveStyles, /\.mobile-chart-inline-actions > button > span \{ display: none; \}/)
  assert.match(responsiveStyles, /\.timeframe-dropdown-trigger \{ padding-inline: 8px; white-space: nowrap; word-break: keep-all; \}/)
  assert.match(componentStyles, /\.timeframe-dropdown \{ position: relative;/)
  assert.match(componentStyles, /\.timeframe-dropdown-menu \{[\s\S]*?position: absolute; z-index: 180; top: calc\(100% \+ 4px\); left: 0;/)
  assert.match(chartWorkspaceSource, /document\.body\.style\.overflow = 'hidden'/)
  assert.match(chartWorkspaceSource, /document\.documentElement\.style\.scrollbarGutter = 'auto'/)
  assert.match(chartWorkspaceSource, /event\.key !== 'Escape'[\s\S]*?setWorkbenchOpen\(false\)/)
  assert.match(marketStyles, /\.chart-workspace-shell\.is-workbench-open \{[\s\S]*?inset: 0;[\s\S]*?width: 100vw;[\s\S]*?height: 100dvh/)
  assert.match(marketStyles, /\.chart-workspace-shell\.is-workbench-open \.chart-slot-toolbar > :not\(\.timeframe-dropdown\) \{ display: none; \}/)
  assert.match(marketStyles, /\.app-shell:has\(\.chart-workspace-shell\.is-workbench-open\) \.topbar,[\s\S]*?\.status-strip,[\s\S]*?display: none !important/)
  assert.match(responsiveStyles, /\.chart-workbench-inspector, \.chart-workspace-shell\.has-workbench-inspector \.chart-workbench-inspector \{ position: absolute;[\s\S]*?left: 8px; width: auto/)
  assert.match(responsiveStyles, /\.chart-slot, \.chart-slot-canvas, \.market-chart-stage, \.market-chart-canvas \{ width: 100%; max-width: 100%; min-width: 0; \}/)
  assert.match(chartWorkspaceSource, /mobileDrawingToolsOpen/)
  assert.match(chartWorkspaceSource, /aria-label=\{mobileDrawingToolsOpen \? '收起画图工具' : '打开画图工具'\}/)
  assert.match(responsiveStyles, /\.drawing-tools-root \{ display: none;/)
  assert.match(responsiveStyles, /\.chart-workspace-shell\.mobile-drawing-tools-open \.drawing-tools-root \{ display: block; \}/)
  assert.match(marketStyles, /@media \(pointer: coarse\) \{[\s\S]*?\.chart-slot \{ grid-template-rows: 44px minmax\(0, 1fr\); \}/)
  assert.match(marketStyles, /\.layout-picker-trigger, \.multi-chart-actions button, \.multi-chart-utility-actions button \{ min-width: 44px; min-height: 44px; height: 44px; \}/)
  assert.match(responsiveStyles, /\.chart-workspace-shell\.is-workbench-open\.mobile-drawing-tools-open \.chart-workbench-body \{ grid-template-rows: minmax\(0, 1fr\); \}/)
  assert.doesNotMatch(pagesSource, /mobile-watchlist-open/)
  assert.match(pagesSource, /className="research-stock-switcher"/)
  assert.match(pagesSource, /stockSwitcherOpen \? 'stock-switcher-open' : ''/)
  assert.match(pagesSource, /mobile-evidence-open/)
  assert.match(pagesSource, /useState\(\(\) => window\.matchMedia\('\(max-width: 600px\)'\)\.matches\)/)
  assert.match(pagesSource, /openTechnicalIndicators[\s\S]*?setMobileEvidenceOpen\(true\)/)
  assert.match(responsiveStyles, /\.watchlist-panel \{ display: none; \}/)
  assert.match(responsiveStyles, /\.market-workspace\.mobile-watchlist-open \.watchlist-panel \{ position: absolute;/)
  assert.match(responsiveStyles, /\.mobile-evidence-panel \{ display: none; \}/)
  assert.match(responsiveStyles, /\.market-workspace\.mobile-evidence-open \.mobile-evidence-panel \{ display: block;/)
  assert.match(responsiveStyles, /\.chart-workspace-shell \{ grid-template-rows: 44px minmax\(0, 1fr\); \}/)
  assert.match(responsiveStyles, /\.chart-settings \{ position: fixed;/)
  assert.match(responsiveStyles, /\.chart-crosshair-card \{ left: 6px; max-width: min\(292px,[\s\S]*?background: color-mix\(in srgb, var\(--surface\) 66%, transparent\)/)
  assert.match(responsiveStyles, /\.layout-picker-popover, \.chart-symbol-popover \{ position: fixed;/)
  assert.match(responsiveStyles, /\.chart-slot-data-status \{ top: auto; right: 66px; bottom: 30px;/)
  assert.match(responsiveStyles, /@media \(max-width: 980px\) and \(max-height: 560px\) and \(orientation: landscape\) \{[\s\S]*?\.market-workspace \.watchlist-panel, \.market-workspace \.instrument-header, \.market-workspace \.mobile-evidence-panel \{ display: none; \}[\s\S]*?\.market-workspace \.chart-frame \{ height: calc\(100dvh - var\(--topbar-height\) - var\(--status-height\) - 58px - env\(safe-area-inset-bottom\)\);/)
  assert.match(responsiveStyles, /@media \(max-width: 980px\) and \(max-height: 560px\) and \(orientation: landscape\) \{[\s\S]*?:root \{ --sidebar-width: 0px; --topbar-height: 50px; --status-height: 31px; \}[\s\S]*?\.mobile-nav \{[\s\S]*?display: grid;[\s\S]*?grid-template-columns: repeat\(4, 1fr\);[\s\S]*?\.app-shell:has\(\.chart-workspace-shell\.is-workbench-open\) \.mobile-nav \{ display: none; \}/)
})

test('market workspace keeps alert controls explicit and local marker visibility does not mutate alerts', () => {
  assert.match(pagesSource, /const \[hiddenAlertIds, setHiddenAlertIds\]/)
  assert.match(pagesSource, /!hiddenAlertIds\.includes\(item\.id\)/)
  assert.match(pagesSource, /toggleAlertMarker/)
  assert.match(pagesSource, /<Eye size=\{15\}/)
  assert.match(pagesSource, /<EyeOff size=\{15\}/)
  assert.match(pagesSource, /<Bell size=\{13\}/)
  assert.match(pagesSource, /<BellOff size=\{13\}/)
  assert.match(pagesSource, /<Trash2 size=\{15\}/)
  assert.match(pagesSource, /item\.is_active === undefined \|\| item\.is_active === true/)
  assert.match(pagesSource, /aria-label=\{`\$\{markerVisible \? '隐藏' : '显示'\}/)
  assert.match(chartWorkspaceSource, /toolbarActions && <span className="multi-chart-utility-actions">/)
  assert.match(chartWorkspaceSource, /slotIsActive && <span className="mobile-chart-inline-actions"/)
  assert.match(chartWorkspaceSource, /typeof alertPrices === 'function' \? alertPrices\(slot\.market, slot\.symbol\)/)
  assert.match(pagesSource, /isAlertForInstrument\(item, market, symbol\)/)
  assert.match(pagesSource, /createPriceAlert\(selected\.symbol, alertPrice, \{ market: selected\.market \}\)/)
  assert.match(pagesSource, /price: 0,/)
  assert.match(pagesSource, /marketQuote\?\.symbol === instrument\.symbol/)
  assert.match(pagesSource, /typeof currentQuote\?\.last === 'number'/)
  assert.match(pagesSource, /setAlertPrice\(currentPrice\)/)
  assert.doesNotMatch(pagesSource, /setAlertPrice\(selectedBase\.price \|\| 0\)/)
  assert.match(pagesSource, /catch \{[\s\S]*?quoteRequestSequence\.current === sequence[\s\S]*?setMarketQuote\(null\)/)
  assert.match(pagesSource, /return \{ \.\.\.selectedBase, price: 0, changePct: 0 \}/)
})

test('market discovery caches each market safely while calendar stays truthful and option data retain explicit groups', () => {
  assert.match(marketOverviewSource, /marketQuoteCache = new Map<Market, MarketQuoteCacheEntry>/)
  assert.match(marketOverviewSource, /fetchOverviewQuotes\(otherMarket, preloadCandidates\)/)
  assert.match(marketOverviewSource, /requestSequence\.current !== sequence/)
  assert.match(marketCalendarSource, /market: Market/)
  assert.doesNotMatch(marketCalendarSource, /PREVIEW_EVENTS/)
  assert.doesNotMatch(marketCalendarSource, /澳洲|英國|日本/)
  assert.match(marketCalendarSource, /真实事件源待接入/)
  assert.match(marketCalendarSource, /不会用预览日期或虚构数字填充/)
  assert.doesNotMatch(marketCalendarSource, /台北|Taipei|Asia\/Taipei/)
  assert.match(optionWorkspaceSource, /className="option-chain-groups"/)
  assert.match(optionWorkspaceSource, /colSpan=\{4\}>Greeks/)
})

test('SelectField is a portalled keyboard listbox with viewport-safe placement', () => {
  assert.match(selectFieldSource, /createPortal/)
  assert.match(selectFieldSource, /role="combobox"/)
  assert.match(selectFieldSource, /role="listbox"/)
  assert.match(selectFieldSource, /window\.addEventListener\('scroll', reposition, true\)/)
  assert.match(selectFieldSource, /document\.addEventListener\('pointerdown', closeOnOutsidePointer\)/)
  assert.match(selectFieldSource, /event\.key === 'ArrowDown'/)
  assert.match(selectFieldSource, /placement === 'bottom'/)
})
