import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import test from 'node:test'

const pagesSource = readFileSync(new URL('../src/pages.tsx', import.meta.url), 'utf8')
const chartWorkspaceSource = readFileSync(new URL('../src/components/ChartWorkspace.tsx', import.meta.url), 'utf8')
const marketOverviewSource = readFileSync(new URL('../src/components/MarketOverview.tsx', import.meta.url), 'utf8')
const marketHeatmapSource = readFileSync(new URL('../src/components/MarketHeatmap.tsx', import.meta.url), 'utf8')
const mainSource = readFileSync(new URL('../src/main.tsx', import.meta.url), 'utf8')
const baseStyles = readFileSync(new URL('../src/styles/base.css', import.meta.url), 'utf8')
const marketStyles = readFileSync(new URL('../src/styles/market.css', import.meta.url), 'utf8')
const operationsStyles = readFileSync(new URL('../src/styles/operations.css', import.meta.url), 'utf8')
const optionStyles = readFileSync(new URL('../src/styles/options.css', import.meta.url), 'utf8')
const responsiveStyles = readFileSync(new URL('../src/styles/responsive.css', import.meta.url), 'utf8')
const componentStyles = readFileSync(new URL('../src/styles/components.css', import.meta.url), 'utf8')
const drawingLayerSource = readFileSync(new URL('../src/components/ChartDrawingLayer.tsx', import.meta.url), 'utf8')
const marketChartSource = readFileSync(new URL('../src/components/MarketChart.tsx', import.meta.url), 'utf8')
const marketCalendarSource = readFileSync(new URL('../src/components/MarketEventCalendar.tsx', import.meta.url), 'utf8')
const selectFieldSource = readFileSync(new URL('../src/components/ui/SelectField.tsx', import.meta.url), 'utf8')
const optionWorkspaceSource = readFileSync(new URL('../src/components/OptionResearchWorkspace.tsx', import.meta.url), 'utf8')
const timeframeDropdownSource = readFileSync(new URL('../src/components/ui/TimeframeDropdown.tsx', import.meta.url), 'utf8')
const welcomeStyles = readFileSync(new URL('../src/styles/welcome.css', import.meta.url), 'utf8')
const indexSource = readFileSync(new URL('../index.html', import.meta.url), 'utf8')
const appSource = readFileSync(new URL('../src/App.tsx', import.meta.url), 'utf8')
const appShellSource = readFileSync(new URL('../src/components/AppShell.tsx', import.meta.url), 'utf8')
const loginPageSource = readFileSync(new URL('../src/pages/LoginPage.tsx', import.meta.url), 'utf8')
const themeSource = readFileSync(new URL('../src/theme.ts', import.meta.url), 'utf8')
const reportsSource = readFileSync(new URL('../src/pages/ReportsPage.tsx', import.meta.url), 'utf8')
const professionalLabSource = readFileSync(new URL('../src/pages/ProfessionalLabPage.tsx', import.meta.url), 'utf8')
const clientSource = readFileSync(new URL('../src/api/client.ts', import.meta.url), 'utf8')
const workspaceContextSource = readFileSync(new URL('../src/api/WorkspaceContext.tsx', import.meta.url), 'utf8')

test('Simplified and Traditional Chinese fonts are bundled locally without Google font runtime failures', () => {
  assert.match(mainSource, /@fontsource-variable\/noto-sans-tc\/wght\.css/)
  assert.match(mainSource, /@fontsource-variable\/noto-sans-sc\/wght\.css/)
  assert.match(mainSource, /@fontsource\/ibm-plex-mono\/latin-700\.css/)
  assert.doesNotMatch(baseStyles, /fonts\.googleapis\.com/)
  assert.match(baseStyles, /--font-hant: 'Noto Sans TC Variable'/)
  assert.match(baseStyles, /--font-hans: 'Noto Sans SC Variable'/)
  assert.match(welcomeStyles, /font-family: var\(--font-ui\)/)
})

test('markets use one controlled canonical inspector without a reserved outer column', () => {
  assert.match(pagesSource, /matchMedia\('\(min-width: 1071px\)'\)/)
  assert.match(pagesSource, /Boolean\(validRequestedInspectorTab\)/)
  assert.match(pagesSource, /validRequestedInspectorTab !== previousRequestedInspectorTab\.current/)
  assert.match(pagesSource, /inspectorOpen=\{inspectorOpen\}/)
  assert.match(pagesSource, /onInspectorOpenChange=\{setInspectorOpen\}/)
  assert.match(pagesSource, /inspectorExtra=\{auxiliaryInspector\}/)
  assert.doesNotMatch(pagesSource, /<aside className="market-inspector">/)
  assert.match(marketStyles, /grid-template-columns: 202px minmax\(0, 1fr\)/)
  assert.doesNotMatch(marketStyles, /\.market-inspector/)
  assert.match(responsiveStyles, /@media \(max-width: 980px\) \{[\s\S]*?\.chart-workbench-inspector \{ position: absolute/)
  assert.doesNotMatch(responsiveStyles, /@media \(max-width: 1070px\)/)
  assert.ok(
    chartWorkspaceSource.indexOf('{inspectorExtra}') < chartWorkspaceSource.indexOf('className="chart-technical-details"'),
    'the task tabs should precede the collapsed technical detail section',
  )
})

test('market discovery pages eight desktop cards in a four by two grid while mobile limits four cards to a snap strip', () => {
  assert.match(marketOverviewSource, /className="market-overview" data-market=\{market\}/)
  assert.match(marketOverviewSource, /const DESKTOP_CARD_PAGE_SIZE = 8/)
  assert.match(marketOverviewSource, /const MOBILE_CARD_LIMIT = 4/)
  assert.match(marketOverviewSource, /shown\.slice\(0, MOBILE_CARD_LIMIT\)/)
  assert.match(marketOverviewSource, /\(cardsPage - 1\) \* DESKTOP_CARD_PAGE_SIZE/)
  assert.match(marketOverviewSource, /overview-card-pagination/)
  assert.match(marketStyles, /grid-template-columns: repeat\(4, minmax\(0, 1fr\)\)/)
  assert.match(responsiveStyles, /\.market-overview \.overview-card-grid \{ grid-template-columns: repeat\(2, minmax\(0, 1fr\)\); \}/)
  assert.match(responsiveStyles, /\.overview-card-grid \{ display: grid; grid-auto-flow: column/)
  assert.match(responsiveStyles, /scroll-snap-type: x mandatory/)
  assert.match(responsiveStyles, /\.overview-card-pagination \{ display: none; \}/)
  assert.match(marketOverviewSource, /K线工作图/)
  assert.match(marketOverviewSource, /variant="label"/)
})

test('market heatmap separates authoritative industry taxonomy from unconnected market themes', () => {
  for (const field of ['taxonomy_source', 'taxonomy_code', 'taxonomy_level', 'label', 'return_pct', 'constituent_count', 'as_of']) {
    assert.match(marketHeatmapSource, new RegExp(field))
  }
  assert.match(marketHeatmapSource, /行业热力图暂不可用/)
  assert.match(marketHeatmapSource, /行业组与行业不会在同一层级混放/)
  assert.match(marketHeatmapSource, /不绘制涨跌方块、不排序，也不提供代表股票/)
  assert.match(marketHeatmapSource, /市场主题 \/ 概念/)
  assert.match(marketHeatmapSource, /“光通信”等市场主题只会进入独立主题合同/)
  assert.doesNotMatch(marketHeatmapSource, /MSCI|S&P|GICS|data-taxonomy-source|data-taxonomy-code|data-direction|代表标的/)
  assert.doesNotMatch(marketOverviewSource, /onOpenSymbol=/)
  assert.match(marketStyles, /\.market-heatmap-empty \{[\s\S]*?border-bottom: 1px solid var\(--border\)/)
})

test('chart controls keep source identity private while retaining the desktop and keyboard contracts', () => {
  assert.doesNotMatch(chartWorkspaceSource, /<select[^>]*时间周期/)
  assert.match(chartWorkspaceSource, /TimeframeDropdown/)
  assert.match(timeframeDropdownSource, /createPortal/)
  assert.match(timeframeDropdownSource, /menuRef/)
  assert.match(timeframeDropdownSource, /optionRefs/)
  assert.match(timeframeDropdownSource, /triggerRef\.current\?\.focus/)
  assert.match(timeframeDropdownSource, /window\.addEventListener\('scroll', reposition, true\)/)
  assert.match(timeframeDropdownSource, /placement === 'top'/)
  assert.match(componentStyles, /timeframe-dropdown-menu/)
  assert.match(chartWorkspaceSource, /displayDataSource\(quote\.source\)/)
  assert.match(pagesSource, /displayDataSource\(payload\.status\.display_source\)/)
  assert.match(pagesSource, /activeTab === '期权证据'.*options-tab-cta/)
  assert.match(chartWorkspaceSource, /<div className="workbench-title">[\s\S]*?<strong>K线工作图<\/strong>[\s\S]*?<WatchlistToggle[\s\S]*?className="workbench-watchlist-toggle"[\s\S]*?<\/div>\s*<div className="multi-chart-layout-picker"/)
  assert.doesNotMatch(chartWorkspaceSource, /definition\.label} · \{marketLabel\(activeSlot\.market\)/)
  assert.match(chartWorkspaceSource, /toolbarActions\?: ReactNode/)
  assert.match(chartWorkspaceSource, /multi-chart-utility-actions/)
  assert.doesNotMatch(chartWorkspaceSource, /marketBrowserOpen|chart-market-browser|multi-chart-footer/)
  assert.doesNotMatch(pagesSource, /chart-toolbar-bottom/)
  assert.match(pagesSource, /toolbarActions=\{<>[\s\S]*?打开价格预警[\s\S]*?技术指标[\s\S]*?图表设置[\s\S]*?<\/>\}/)
  assert.match(marketStyles, /\.chart-frame \{[\s\S]*?height: clamp\(600px, calc\(100dvh - var\(--topbar-height\) - var\(--status-height\) - 72px\), 860px\);[\s\S]*?min-height: 600px;/)
  assert.doesNotMatch(pagesSource, /instrument-watch-toggle/)
  assert.match(componentStyles, /\.timeframe-dropdown-trigger \{[\s\S]*?height: 32px/)
  assert.match(componentStyles, /@media \(pointer: coarse\) \{[\s\S]*?\.timeframe-dropdown-trigger,[\s\S]*?min-height: 44px/)
  assert.match(marketStyles, /@media \(pointer: coarse\) \{[\s\S]*?\.chart-view-controls button \{ width: 44px; height: 44px; \}/)
  assert.match(marketStyles, /\.drawing-tool-dock::-webkit-scrollbar \{ display: none; \}/)
  assert.match(drawingLayerSource, /scrollHorizontalDock/)
  assert.match(drawingLayerSource, /matchMedia\(horizontalDockQuery\)/)
  assert.doesNotMatch(responsiveStyles, /\.multi-chart-layouts/)
  assert.match(responsiveStyles, /\.multi-chart-layout-picker/)
  assert.match(responsiveStyles, /\.drawing-tool-dock button \{ width: 44px; height: 44px;/)
  assert.match(reportsSource, /displayDataSource\(workspace\.data\?\.performance\.mark_source/)
  assert.match(professionalLabSource, /displayDataSource\(workspace\.data\?\.market_data\.display_source/)
  assert.doesNotMatch(reportsSource, /recorded_system_snapshot/)
  assert.match(operationsStyles, /\.report-layout \{ align-items: stretch; \}/)
})

test('risk rings and the options workbench retain their institutional viewport contracts', () => {
  assert.match(operationsStyles, /\.lab-risk-workbench/)
  assert.match(operationsStyles, /\.metric-ring-dial/)
  assert.match(operationsStyles, /conic-gradient\(var\(--metric-ring-color\) calc\(var\(--metric-ring-value\) \* 1%\)/)
  assert.match(optionStyles, /\.lab-tab-options > \.page-header/)
  assert.match(optionStyles, /height: calc\(100dvh - var\(--topbar-height\) - var\(--status-height\)\)/)
  assert.match(optionStyles, /align-items: stretch/)
  assert.match(optionStyles, /height: 100%; max-height: 100%; grid-template-rows: auto minmax\(0, 1fr\)/)
  assert.match(optionStyles, /max-height: 560px/)
  assert.match(optionStyles, /\.lab-tab-options \.option-workbench \{ height: auto; min-height: 0; grid-row: -2 \/ -1; \}/)
  assert.match(optionStyles, /\.option-chart-panel\[data-detail-active='true'\],[\s\S]*?\.option-combination-panel\[data-detail-active='true'\] \{ display: none; \}/)
  assert.match(optionStyles, /\.lab-tab-options \.option-workbench \{ height: auto; min-height: 220px; grid-row: -2 \/ -1; grid-template-rows: 40px minmax\(0, 1fr\); gap: 4px; \}/)
})

test('theme canvas is applied before React and shared by public and console controls', () => {
  assert.match(baseStyles, /--canvas: #0b0d0c/)
  assert.match(baseStyles, /:root\[data-theme='light'\] \{[\s\S]*?--canvas: #dbe2db/)
  assert.match(baseStyles, /--workspace: #e3e9e2[\s\S]*?--surface: #edf1eb[\s\S]*?--surface-raised: #e8ede7[\s\S]*?--surface-inset: #d4ddd4/)
  assert.doesNotMatch(baseStyles, /--surface-raised: #(?:fff|ffffff)/)
  assert.match(indexSource, /localStorage\.getItem\('ciclotrade\.theme'\) === 'light'/)
  assert.match(indexSource, /root\.dataset\.theme = theme/)
  assert.match(indexSource, /themeColor\.setAttribute\('content', theme === 'light' \? '#dbe2db' : '#0b0d0c'\)/)
  assert.match(themeSource, /THEME_CANVAS[\s\S]*?dark: '#0b0d0c'[\s\S]*?light: '#dbe2db'/)
  assert.match(appSource, /from '\.\/theme'/)
  assert.match(appShellSource, /from '\.\.\/theme'/)
  assert.match(loginPageSource, /from '\.\.\/theme'/)
  assert.doesNotMatch(appSource, /ciclotrade\.theme/)
  assert.doesNotMatch(appShellSource, /theme-color/)
  assert.doesNotMatch(loginPageSource, /theme-color/)
})

test('coarse pointers retain 44px option and authentication controls without reducing landscape workbench space', () => {
  assert.match(welcomeStyles, /@media \(pointer: coarse\) \{[\s\S]*?\.login-mode-tabs button \{ min-height: 44px; \}/)
  assert.match(optionStyles, /@media \(pointer: coarse\) \{[\s\S]*?\.option-task-tabs button,[\s\S]*?\.option-chart-controls select \{ min-height: 44px; \}/)
  assert.match(optionStyles, /\.lab-tab-options \.option-workbench \{ grid-template-rows: 44px minmax\(0, 1fr\); \}/)
  assert.match(optionStyles, /\.lab-tab-options \.option-workbench \{ height: auto; min-height: 220px;/)
})

test('market refresh effects keep stable lifetimes and never expose raw provider freshness', () => {
  assert.match(chartWorkspaceSource, /const primaryQuoteExternallyManaged = initialQuote !== undefined/)
  assert.match(chartWorkspaceSource, /primaryQuoteExternallyManaged, primarySlotId, quoteFetchSignature/)
  assert.doesNotMatch(chartWorkspaceSource, /\[initialMarket, initialQuote, initialSymbol, loadQuote/)
  assert.match(chartWorkspaceSource, /if \(!hasPreviousQuote\) \{[\s\S]*?读取报价中/)
  assert.match(chartWorkspaceSource, /quoteInFlightRef[\s\S]*?previousRequest\?\.identity === identity[\s\S]*?previousRequest\.request/)
  assert.match(marketOverviewSource, /displayDeliveryDelay\(payload\.status\.delivery_delay_minutes\) \|\| displayFreshness/)
  assert.match(appShellSource, /const marketFreshness = displayFreshness\(marketStatus\?\.freshness\)/)
  assert.doesNotMatch(appShellSource, /marketStatus\?\.freshness\s*\?\?/)
  assert.match(clientSource, /request<unknown>\('\/api\/rewrite\/v1\/market\/status'\)/)
  assert.match(clientSource, /validMarketStatusPayload/)
  assert.match(workspaceContextSource, /createVisibilityPolling\(async \(\) => \{[\s\S]*?fetchMarketStatus\(\)[\s\S]*?\}, 15_000\)/)
})

test('authenticated market pages fail closed and chart timestamps use the fixed Hong Kong display clock', () => {
  assert.match(pagesSource, /loadCandles=\{marketDataEnabled \? loadWorkspaceCandles : undefined\}/)
  assert.match(marketOverviewSource, /行情连接未启用，不显示演示行情/)
  assert.match(marketOverviewSource, /marketDataEnabled: boolean/)
  assert.match(marketOverviewSource, /demoMode: boolean/)
  assert.match(marketOverviewSource, /if \(demoMode\)/)
  assert.match(chartWorkspaceSource, /市场未连接|marketLabel\(slot\.market\)/)
  assert.doesNotMatch(chartWorkspaceSource, /className="chart-quick-timeframes"/)
  assert.doesNotMatch(chartWorkspaceSource, /chart-range-presets|RANGE_PRESETS/)
  assert.doesNotMatch(marketStyles, /chart-range-presets|grid-template-rows: auto minmax\(0, 1fr\) 28px/)
  assert.match(marketChartSource, /timeZone: 'Asia\/Hong_Kong'/)
  assert.match(marketChartSource, /typeof value === 'object'/)
  assert.match(marketChartSource, /日线以美国交易日归档/)
  assert.match(marketChartSource, /chart-crosshair-card/)
})

test('market workspace keeps alert controls explicit and local marker visibility does not mutate alerts', () => {
  assert.match(pagesSource, /const \[hiddenAlertIds, setHiddenAlertIds\]/)
  assert.match(pagesSource, /!hiddenAlertIds\.includes\(item\.id\)/)
  assert.match(pagesSource, /toggleAlertMarker/)
  assert.match(pagesSource, /<Eye size=\{16\}/)
  assert.match(pagesSource, /<EyeOff size=\{16\}/)
  assert.match(pagesSource, /<Bell size=\{13\}/)
  assert.match(pagesSource, /<BellOff size=\{13\}/)
  assert.match(pagesSource, /<Trash2 size=\{16\}/)
  assert.match(pagesSource, /aria-label=\{`\$\{markerVisible \? '隐藏' : '显示'\}/)
  assert.match(chartWorkspaceSource, /toolbarActions && <span className="multi-chart-utility-actions">/)
  assert.match(chartWorkspaceSource, /typeof alertPrices === 'function' \? alertPrices\(slot\.market, slot\.symbol\)/)
  assert.match(pagesSource, /isAlertForInstrument\(item, market, symbol\)/)
  assert.match(pagesSource, /createPriceAlert\(selected\.symbol, alertPrice, \{ market: selected\.market \}\)/)
})

test('market discovery caches each market safely while calendar and option data retain explicit groups', () => {
  assert.match(marketOverviewSource, /marketQuoteCache = new Map<Market, MarketQuoteCacheEntry>/)
  assert.match(marketOverviewSource, /fetchOverviewQuotes\(otherMarket, preloadCandidates\)/)
  assert.match(marketOverviewSource, /requestSequence\.current !== sequence/)
  assert.match(marketCalendarSource, /market: Market/)
  assert.match(marketCalendarSource, /PREVIEW_EVENTS\.filter\(\(item\) => item\.market === market\)/)
  assert.doesNotMatch(marketCalendarSource, /澳洲|英國|日本/)
  assert.match(marketCalendarSource, /財報日期預覽/)
  assert.match(marketCalendarSource, /香港时区预览/)
  assert.doesNotMatch(marketCalendarSource, /台北|Taipei|Asia\/Taipei/)
  assert.match(optionWorkspaceSource, /className="option-chain-groups"/)
  assert.match(optionWorkspaceSource, /colSpan=\{4\}>Greeks/)
})

test('SelectField is a portalled keyboard listbox with viewport-safe placement', () => {
  assert.match(selectFieldSource, /createPortal/)
  assert.match(selectFieldSource, /role="combobox"/)
  assert.match(selectFieldSource, /role="listbox"/)
  assert.match(selectFieldSource, /window\.addEventListener\('scroll', reposition, true\)/)
  assert.match(selectFieldSource, /document\.addEventListener\('pointerdown', closeOnOutsidePointer\)/)
  assert.match(selectFieldSource, /event\.key === 'ArrowDown'/)
  assert.match(selectFieldSource, /placement === 'bottom'/)
})
