import { authenticatedJsonRequest } from './client.ts'

export type ReferralCurrency = 'HKD'
export type ReferralCommissionType = 'initial_purchase' | 'renewal' | 'upgrade'
export type ReferralCommissionStatus = 'pending' | 'withdrawable' | 'partially_clawed_back' | 'clawed_back'
export type ReferralWithdrawalStatus = 'submitted' | 'approved' | 'rejected' | 'paid' | 'system_cancelled'
export type ReferralTimelineType = 'registration' | 'commission_pending' | 'commission_withdrawable' | 'clawback' | 'withdrawal_submitted' | 'withdrawal_approved' | 'withdrawal_rejected' | 'withdrawal_paid' | 'withdrawal_cancelled'

export interface ReferralWithdrawal { withdrawal_id: string; amount_minor: number; currency: ReferralCurrency; status: ReferralWithdrawalStatus; submitted_at: string; reviewed_at: string | null; approved_at: string | null; paid_at: string | null; rejection_reason: string | null }
export interface ReferralPortal {
  program: { enabled: boolean; currency: ReferralCurrency; policy_version: string; first_rate_bps: number; renewal_rate_bps: number; upgrade_rate_bps: number; hold_days: number; minimum_withdrawal_minor: number }
  invite: { invite_code: string; invite_link: string; qr_payload: string }
  balances: { earned_total_minor: number; pending_minor: number; withdrawable_minor: number; reserved_minor: number; paid_minor: number; clawed_back_total_minor: number; debt_minor: number }
  trends: { windows: Array<{ days: 7 | 30 | 90; visits: number; registrations: number; settled_orders: number; gross_amount_minor: number; earned_amount_minor: number; clawed_back_minor: number }> }
  funnel: { visits_30d: number; registrations_30d: number; settled_referrals_30d: number; registration_rate_bps: number; settlement_rate_bps: number }
  referrals: Array<{ referral_id: string; user_masked: string; joined_at: string; settled_orders: number; last_settled_at: string | null }>
  commissions: Array<{ commission_id: string; recharge_id: string; commission_type: ReferralCommissionType; gross_amount_minor: number; rate_bps: number; earned_amount_minor: number; clawed_back_minor: number; net_amount_minor: number; status: ReferralCommissionStatus; settled_at: string; available_at: string }>
  withdrawals: ReferralWithdrawal[]
  timeline: Array<{ event_id: string; event_type: ReferralTimelineType; public_reference: string; amount_minor: number | null; occurred_at: string }>
}
export type ReferralPortalTransport = (path: string, init?: RequestInit) => Promise<unknown>
function isRecord(value: unknown): value is Record<string, unknown> { return Boolean(value) && typeof value === 'object' && !Array.isArray(value) }
function exactKeys(value: Record<string, unknown>, expected: readonly string[]) { const keys = Object.keys(value); return keys.length === expected.length && keys.every((key) => expected.includes(key)) }
function minor(value: unknown): value is number { return Number.isSafeInteger(value) && Number(value) >= 0 }
function timestamp(value: unknown): value is string { return typeof value === 'string' && /\+08:00$/.test(value) && Number.isFinite(Date.parse(value)) }
function opaque(value: unknown): value is string { return typeof value === 'string' && /^[A-Za-z0-9_-]{6,128}$/.test(value) }
function validWithdrawal(value: unknown): value is ReferralWithdrawal { return isRecord(value) && exactKeys(value, ['withdrawal_id', 'amount_minor', 'currency', 'status', 'submitted_at', 'reviewed_at', 'approved_at', 'paid_at', 'rejection_reason']) && opaque(value.withdrawal_id) && minor(value.amount_minor) && value.currency === 'HKD' && ['submitted', 'approved', 'rejected', 'paid', 'system_cancelled'].includes(String(value.status)) && timestamp(value.submitted_at) && [value.reviewed_at, value.approved_at, value.paid_at].every((item) => item === null || timestamp(item)) && (value.rejection_reason === null || (typeof value.rejection_reason === 'string' && value.rejection_reason.length <= 500)) }

/** Exact public contract: rejects DB identifiers, personal data and private payout fields. */
export function decodeReferralPortal(value: unknown): ReferralPortal {
  if (!isRecord(value) || !exactKeys(value, ['program', 'invite', 'balances', 'trends', 'funnel', 'referrals', 'commissions', 'withdrawals', 'timeline'])) throw new Error('推广中心响应格式无效。')
  if (!isRecord(value.program) || !exactKeys(value.program, ['enabled', 'currency', 'policy_version', 'first_rate_bps', 'renewal_rate_bps', 'upgrade_rate_bps', 'hold_days', 'minimum_withdrawal_minor']) || typeof value.program.enabled !== 'boolean' || value.program.currency !== 'HKD' || typeof value.program.policy_version !== 'string' || ![value.program.first_rate_bps, value.program.renewal_rate_bps, value.program.upgrade_rate_bps, value.program.hold_days, value.program.minimum_withdrawal_minor].every(minor)) throw new Error('推广计划字段无效。')
  if (!isRecord(value.invite) || !exactKeys(value.invite, ['invite_code', 'invite_link', 'qr_payload']) || !opaque(value.invite.invite_code) || ![value.invite.invite_link, value.invite.qr_payload].every((item) => typeof item === 'string')) throw new Error('推广资产字段无效。')
  if (!isRecord(value.balances) || !exactKeys(value.balances, ['earned_total_minor', 'pending_minor', 'withdrawable_minor', 'reserved_minor', 'paid_minor', 'clawed_back_total_minor', 'debt_minor']) || !Object.values(value.balances).every(minor)) throw new Error('推广结算字段无效。')
  if (!isRecord(value.trends) || !exactKeys(value.trends, ['windows']) || !Array.isArray(value.trends.windows) || value.trends.windows.length !== 3 || !value.trends.windows.every((item) => isRecord(item) && exactKeys(item, ['days', 'visits', 'registrations', 'settled_orders', 'gross_amount_minor', 'earned_amount_minor', 'clawed_back_minor']) && [7, 30, 90].includes(Number(item.days)) && [item.visits, item.registrations, item.settled_orders, item.gross_amount_minor, item.earned_amount_minor, item.clawed_back_minor].every(minor))) throw new Error('推广趋势字段无效。')
  if (!isRecord(value.funnel) || !exactKeys(value.funnel, ['visits_30d', 'registrations_30d', 'settled_referrals_30d', 'registration_rate_bps', 'settlement_rate_bps']) || !Object.values(value.funnel).every(minor)) throw new Error('推广漏斗字段无效。')
  if (!Array.isArray(value.referrals) || !value.referrals.every((item) => isRecord(item) && exactKeys(item, ['referral_id', 'user_masked', 'joined_at', 'settled_orders', 'last_settled_at']) && opaque(item.referral_id) && typeof item.user_masked === 'string' && timestamp(item.joined_at) && minor(item.settled_orders) && (item.last_settled_at === null || timestamp(item.last_settled_at)))) throw new Error('推广邀请字段无效。')
  if (!Array.isArray(value.commissions) || !value.commissions.every((item) => isRecord(item) && exactKeys(item, ['commission_id', 'recharge_id', 'commission_type', 'gross_amount_minor', 'rate_bps', 'earned_amount_minor', 'clawed_back_minor', 'net_amount_minor', 'status', 'settled_at', 'available_at']) && opaque(item.commission_id) && opaque(item.recharge_id) && ['initial_purchase', 'renewal', 'upgrade'].includes(String(item.commission_type)) && [item.gross_amount_minor, item.rate_bps, item.earned_amount_minor, item.clawed_back_minor, item.net_amount_minor].every(minor) && ['pending', 'withdrawable', 'partially_clawed_back', 'clawed_back'].includes(String(item.status)) && timestamp(item.settled_at) && timestamp(item.available_at))) throw new Error('推广佣金字段无效。')
  if (!Array.isArray(value.withdrawals) || !value.withdrawals.every(validWithdrawal)) throw new Error('推广提现字段无效。')
  if (!Array.isArray(value.timeline) || !value.timeline.every((item) => isRecord(item) && exactKeys(item, ['event_id', 'event_type', 'public_reference', 'amount_minor', 'occurred_at']) && opaque(item.event_id) && ['registration', 'commission_pending', 'commission_withdrawable', 'clawback', 'withdrawal_submitted', 'withdrawal_approved', 'withdrawal_rejected', 'withdrawal_paid', 'withdrawal_cancelled'].includes(String(item.event_type)) && opaque(item.public_reference) && (item.amount_minor === null || minor(item.amount_minor)) && timestamp(item.occurred_at))) throw new Error('推广时间线字段无效。')
  return value as unknown as ReferralPortal
}

export interface ReferralApi { loadPortal: (signal?: AbortSignal) => Promise<ReferralPortal>; requestWithdrawal: (input: { amount_minor: number; currency: ReferralCurrency }, idempotencyKey: string, signal?: AbortSignal) => Promise<{ withdrawal: ReferralWithdrawal; balances: Pick<ReferralPortal['balances'], 'withdrawable_minor' | 'reserved_minor' | 'debt_minor'> }> }
export function createReferralApi(transport: ReferralPortalTransport = authenticatedJsonRequest): ReferralApi { return { async loadPortal(signal) { return decodeReferralPortal(await transport('/api/rewrite/v1/referrals/portal', { method: 'GET', cache: 'no-store', signal })) }, async requestWithdrawal(input, idempotencyKey, signal) { if (!Number.isSafeInteger(input.amount_minor) || input.amount_minor < 1 || !/^[A-Za-z0-9_-]{8,128}$/.test(idempotencyKey)) throw new Error('提现申请字段无效。'); const value = await transport('/api/rewrite/v1/referrals/withdrawals', { method: 'POST', headers: { 'Idempotency-Key': idempotencyKey }, body: JSON.stringify(input), signal }); if (!isRecord(value) || !exactKeys(value, ['withdrawal', 'balances']) || !validWithdrawal(value.withdrawal) || !isRecord(value.balances) || !exactKeys(value.balances, ['withdrawable_minor', 'reserved_minor', 'debt_minor']) || !Object.values(value.balances).every(minor)) throw new Error('提现响应格式无效。'); return value as { withdrawal: ReferralWithdrawal; balances: Pick<ReferralPortal['balances'], 'withdrawable_minor' | 'reserved_minor' | 'debt_minor'> } } } }
export const referralApi = createReferralApi()
